# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, default='#000000', max_length=7, verbose_name='Cor')),
                ('label', models.CharField(max_length=5, verbose_name='C\xf3digo')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
            },
        ),
    ]
