# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='C\xf3digo')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('linhas', models.ManyToManyField(related_name='paradas', to='malha.Linha')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
    ]
