# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malha', '0002_parada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
