# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malha', '0003_auto_20160627_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malha.Linha')),
            ],
            options={
                'verbose_name': 'Ve\xedculos',
                'verbose_name_plural': 'Ve\xedculos',
            },
        ),
    ]
