# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malha', '0005_auto_20160704_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
