# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-04 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malha', '0006_auto_20160704_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParadaVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_chegada', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Chegada')),
                ('tempo_saida', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Sa\xedda')),
                ('instante', models.DateTimeField(blank=True, null=True, verbose_name='Instante')),
                ('distancia', models.PositiveIntegerField(default=0, verbose_name='Dist\xe2ncia')),
                ('nome_destino', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Destino')),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malha.Parada')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malha.Veiculo')),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='paradas',
            field=models.ManyToManyField(related_name='veiculos', through='malha.ParadaVeiculo', to='malha.Parada'),
        ),
    ]
