# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malha', '0007_auto_20160704_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='lotacao',
            field=models.IntegerField(default=0, verbose_name='Lota\xe7\xe3o'),
        ),
    ]
